spring:
  application:
    name: cosmo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cosmo?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: false
    open-in-view: false
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration

server:
  port: 8080

security:
  jwt:
    token:
      secret-key: "53cr3t" # Replace with a strong, randomly generated secret
      expire-length: 3600000 # 1 hour in milliseconds
      refresh-token:
        expire-length: 7200000 # 2 hours in milliseconds

spring-doc:
  paths-to-match: /api/**
  swagger-ui:
    use-root-path: true