INSERT INTO empresa (nome, estado) VALUES
('Azza Telecom', 'SP'),
('Webby Internet - SP', 'SP'),
('Webby Internet - PR', 'PR'),
('Webby Internet - MS', 'MS'),
('Webby Internet - RJ', 'RJ'),
('Multiplay', 'CE'),
('Cabo Telecom - RN', 'RN'),
('Cabo Telecom - PB', 'PB'),
('Outcenter - SP', 'SP'),
('Outcenter - MG', 'MG'),
('Outcenter - BA', 'BA'),
('Starweb - SP', 'SP'),
('Starweb - MG', 'MG'),
('Starweb - BA', 'BA'),
('Webnet - SP', 'SP'),
('Webnet - MG', 'MG'),
('Webnet - BA', 'BA'),
('Conexão - MG', 'MG'),
('Conexão - SP', 'SP'),
('Waynet - MG', 'MG'),
('Waynet - SP', 'SP');
